name: CI

on:
  push:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  node16:
    name: Node 16
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: checkout node
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - run: npm install
  node18:
    name: Node 18
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: checkout node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  node20:
    name: Node 20
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: checkout node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run lint
      - run: npm run cs
      - name: sonarcloud.io
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
